# this is how you configure zappr
# a more exhaustive description is at
# https://zappr.readthedocs.io/en/latest/setup

# uncomment this if you want to change anything
approvals:
  pattern: "(:\\+1:|👍|\\+1|approved|approve)"
  # check will succeed if there are 2 approvals from
  # egineer or lead people
  minimum: 2
  groups:
    # check will fail if there is not at least 2 approval
    # from enineer persons
    engineer:
      minimum: 2
      from:
        users:
          - bearfact
          - bradpickensdesign
          - BriannaGreene
          - cnb3
          - EdgarCordova
          - mrandyclark
          - siennamw
          - tom-con
          - cat-plevak
          - Brady-Conn
          - jan-mcsparin
